name: Terraform CI Destroy

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to destroy (dev/staging/prod)"
        required: true
        default: "dev"

jobs:
  terraform-destroy:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ap-south-1
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan Destroy
        run: terraform plan -destroy -var-file=env/${{ github.event.inputs.environment }}.tfvars

      - name: Terraform Destroy
        run: terraform destroy -auto-approve -var-file=env/${{ github.event.inputs.environment }}.tfvars